CREATE TABLE "public"."test_items" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "test_items_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."test_items"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public test access" ON "public"."test_items"
  FOR SELECT
  TO PUBLIC
  USING (true);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."test_items" TO "anon", "authenticated", "postgres", "service_role";

